### ISSUE TITLE
Does caching work on deploys for you?

### ISSUE THREAD

**Issue by jamessimone** [d4rekanguok/gatsby-remark-images-anywhere#11] opened 2019-09-24 18:32 UTC
Hi there,

Sorry to submit a new issue with this but I was wondering if you use Netlify and if you’ve found your caching strategy effective within Netlify. I had a very similar plugin using touchNode and media caching keys which works locally for me, but if I add console statements logging out the caching part in your plugin to see if, when using Netlify, the cache within the plugin is actually found and used ... but no dice. Every deploy the images get redownloaded, unfortunately. Any insight you can offer on how to actually get the cache working on Netlify would be amazing. If you don’t use Netlify ... sorry for bothering you, and thanks for your time!

**Comment by d4rekanguok** [comment] 2019-09-25 03:11
Hi @jamessimone, nice to see you here -- @fartinmartin shared your article in #2!

The site I made this plugin for is still in development (also deployed on Netlify), so it uses very minimal amount of images. It is possible that the images are not cached but I didn't notice. Also, I'm sure you meant to getting the cache to work in conjunction with the plugin `gatsby-plugin-netlify-cache`, since Netlify completely cleans the directory between builds?

`createRemoteFileNode` download & store the file in `.cache` dir <sup>[source](https://github.com/gatsbyjs/gatsby/blob/d7656728f2e567ee518ab8a1f23fb108b5650a78/packages/gatsby-source-filesystem/src/create-remote-file-node.js#L228)</sup>, so the default configuration of `gatsby-plugin-netlify-cache` should work.

However I don't think the transformation results are stored in cached, meaning you'd still be running sharp transformation on those downloaded images. Perhaps [adding `public` directory to cache](https://github.com/axe312ger/gatsby-plugin-netlify-cache#cachepublic---default-false) could work?

I would love to look deeper into this issue, please let me know if you find anything!

**Comment by jamessimone** [comment] 2019-09-25 10:32
@d4rekanguok aha, I hadn't seen that other issue because the title didn't seem to have anything to do with caching.

I'm using a site with, let's say, a medium number of images - between 100-200 images. I am also referring to using the `gatsby-plugin-netlify-cache` plugin, as you mentioned. I have had an issue opened with that plugin for quite some time now, because I don't know why (if it is truly caching the entirety of `.cache`) the remote images would need to be re-downloaded on every run. You can verify that this does indeed happen by logging your own code out where the cache is checked. Locally in development / building, the cache will work correctly and the image transformation results are also stored (seemingly, given the extremely minimal build times, but, again, with even the moderate number of images I have, the times are extremely noticeable because `sharp` takes upwards of 6 minutes to transform my images, your own results may not be as noticeable yet if you only have a few images ...)

Anyway - I really wanted to thank you for your prompt response. Next up I guess I have to just fork the `gatsby-plugin-netlify-cache`, the code for which I pretty much know by heart at this point considering that I have been trying to debug this issue intermittently for months.  I was hopeful that when I implemented the storing and optimizing of remote images, my implementation was just as fault, but after having ported over to (my forked version, so I could log out the caching statements on netlify) your version, I'm afraid the caching issue was still presented. While it's not urgent, given that Netlify builds cap at 15 minutes run time, it also means that I can't use `WEPB` images because the additional transformation time for these images kills my build. Oh well! 

I'll leave this issue open in case you have any other reply / thoughts on the matter, but since it's not with your code feel free to Close and comment when you do 😄

**Comment by d4rekanguok** [comment] 2019-10-04 16:56
@jamessimone I got good news & bad news!

Good news: I successfully reproduced your issue, even in local development. It turned out my cache handling was garbage & I managed to fixed it.

Bad news:
- However there's seems to be a bug in Gatsby that prevents the plugin to works properly. `createRemoteFileNode` calls `createNode` internally, but for whatever reasons, it somehow was passed an options... that override a very important attribute that'll trigger the API runner, therefore the file node was never stored in Gatsby node store, and therefore... it was never cached.

Fixing it was simple -- just ensure the important attribute won't be overridden. I did this, and the plugin successfully caches the remote images. However it's a bandage solution. I'll file an issue over gatsby & let you know when it's resolved.

So the issue is not at `gatsby-plugin-netlify-cache`!

**Comment by jamessimone** [comment] 2019-10-04 17:17
@d4rekanguok - you are a hero. What was the issue with your caching? It sounds like you both changed something with the plugin and have to resolve this issue with Gatsby — is there an associated commit here in your repo? Either way, so so grateful that you managed to track down what was going on, I can’t  wait to see and hear more.

**Comment by d4rekanguok** [comment] 2019-10-04 17:31
@jamessimone My cache handling was faulty! 

So the plugin only works properly in a fresh build. In subsequent build (with cache), it fails to handle the case where the remote image was cached, but its node was gone (stale, garbage collected, broken cache, etc.). 

I was happy to fix this, however this is when I found out that the node returned by `createRemoteFileNode` from `gatsby-source-filesystem` was never stored in Gatsby's node stores. This led to a 2-hour ride of adding console.log to gatsby's redux node api to find out what happened. I traced it down to `actions.createNode`; where it failed to call the runner API...and then I found out that `createNode` accepts a third arguments called `actionOptions`, but this actionOptions contain properties that override the important dispatcher `type`. So instead of dispatching this data:

```
{
  type: "CREATE_NODE",
  payload: { id: "our-precious-remote-image-file-node-id", ...}
}
```

it sends this:
{
  type: { name: 'imageSharp', children: [...] } // <<--- wth?
  payload: { id: "our-precious-remote-image-file-node-id", ...}
}
... and the node was never made it to the other end. So I ensure `type` was preserved, and I can see the node being fetched from cache instead of being re-downloaded.

I'll push a update to this repo & also file the bandage solution as an issue to gatsby & link it here in 10', so you can try it out too if you're interested!

**Comment by jamessimone** [comment] 2019-10-04 17:40
Bravo. Looking forward to it - and again, much appreciated

**Comment by d4rekanguok** [comment] 2019-10-04 18:15
I've filed the bug here: https://github.com/gatsbyjs/gatsby/issues/18136

I detailed the step for bug reproduction there as well.

If you're interested to see my faulty cache handling, it's fixed in [this commit](https://github.com/d4rekanguok/gatsby-remark-images-anywhere/commit/e680880533ea7ab6c21428c80746ee9c0d6ec978)

Hopefully we'll see a fix/solution soon!

And finally, thank you for trying this plugin out! I wouldn't have caught this if you didn't file this issue here -- thank you so much for making this plugin better.

**Comment by jamessimone** [comment] 2019-10-04 18:27
Of course. Thanks for making open source all the better — do you want me to close the issue or shall we wait for the core gatsby issue to be resolved? I will take a look at the bug you filed; perhaps it’s something I’ll be able to help with!

**Comment by d4rekanguok** [comment] 2019-10-04 18:34
Let's wait for the issue in gatsby repo to resolve, this issue is actually pretty important!

**Comment by d4rekanguok** [comment] 2019-10-08 06:49
I've just realized it's hacktoberfest right now (signed up as soon as I found out), so the maintainers are probably floored with new PRs' -- I filed one myself in the hope that it'll facilitate the discussion around the issue.

**Comment by jamessimone** [comment] 2019-10-08 11:25
Great job getting this taken care of! Looks like @pieh just published the fix in the latest version of Gatsby

**Comment by d4rekanguok** [comment] 2019-10-08 13:23
Nice, I've just seen that! @jamessimone would you take this plugin out for a test drive on Netlify?

**Comment by jamessimone** [comment] 2019-10-08 14:39
@d4rekanguok  just referenced this in https://github.com/jamessimone/gatsby-remark-images-anywhere/pull/1 - unfortunately I will have limited connectivity in the coming days, but I wanted to show you my own fork in the event that you noticed something amiss that would otherwise be messing with the plugin. Unfortunately, even with the latest issue of Gatsby - which should have the code merged in - the Netlify builds still don't seem to find the cache.

**Comment by d4rekanguok** [comment] 2019-10-08 14:45
@jamessimone Sorry to hear that - :( I'll check out your fork. Do you have something minimal available that I can test with netlify?

**Comment by jamessimone** [comment] 2019-10-08 15:51
I will draft something up for you — might be tomorrow as I am traveling today. Thank you again for your help and sorry for the delay!

**Comment by d4rekanguok** [comment] 2019-10-08 15:57
No worries friend -- with Netlify setting up limit for build time now, this is an issue that's very close to my wallet!

**Comment by jamessimone** [comment] 2019-10-08 16:22
Ha tell me about it, I have nearly ~200 images in my production build that are hosted remotely, and my build should only take around 1 minute if everything is cached properly but right now I’m closer to 9 minutes than I am to 8 ... I think with the new build limit times everyone is scrambling!

**Comment by jamessimone** [comment] 2019-10-09 18:47
@d4rekanguok I started making the smallest possible example repo possible, modifying an example repo I had made a while back: https://github.com/jamessimone/gatsby-remote-images-example

I copied over my modifications to your repo into the local plugin ... and ... not even the starting console.log statements were reached. Confused, I even changed my package json file to include a reference to your repo, and copied over the config object from your repo ... no dice. Not really clear what the issue is, haha, but fairly frustrated after over an hour debugging what should have been a seemingly plug and play situation. If you’ve got the chance and want to take a gander, great. Otherwise, over the next few days I will hopefully have more time to continue debugging until I figure out what the hell is going on with this seemingly accursed repo haha.

**Comment by d4rekanguok** [comment] 2019-10-10 04:07
@jamessimone Confirmed -- cache was not restored if `.cache` folder was removed & restored between build.

I tested this by setting up a remote image server deployed to heroku, then watch the log as I trigger netlify deploy. The image server get image request on every build, even with cache folder being restored.

We can actually test this locally, by tricking `gatsby-plugin-netlify-cache` to think that it's in Netlify environment:

```bash
gatsby clean && NETLIFY_BUILD_BASE=\"../netlify\" gatsby build
```

This way we won't have to deploy to cloud services to test the issue - it's definitely something within Gatsby. I'll take a deeper look when I can...

If you'd like to test it yourself, you can try my set up [over here](https://github.com/d4rekanguok/gatsby-remote-images-debug).

Run `yarn start:server` in a pane & run `yarn test:cache` in another to watch log from image server & gatsby.

**Comment by d4rekanguok** [comment] 2019-10-10 04:31
wait a minute, it could still be an issue with this plugin -- checking again...

**Comment by d4rekanguok** [comment] 2019-10-10 07:12
Ok, I've found out why `gatsby-plugin-netlify-cache` is not working.

- On bootstrap, gatsby decide whether it should empty the cache or not by comparing a hash created from all plugins. It read the persisted hash (`PLUGINS_HASH`) from the `.cache` <sup>[source](https://github.com/gatsbyjs/gatsby/blob/561d33e2e491d3971cb2a404eec9705a5a493602/packages/gatsby/src/bootstrap/index.js#L183)</sup>.

- If the new calculated `PLUGINS_HASH` is different than the one it retrieved from cache, it'll empty the cache folder.

**The problem:**

Gatsby initialize the store _before_ the `preInit` hook, where `gatsby-plugin-netlify-cache` does its magic. This means the persisted redux store wasn't there when gatsby init the redux store, so the `oldPluginHash` is always `undefined`.

I guess to solve this, we can propose Gatsby to somehow allow a new hook that'll run before store initialization. But that's redundant, since we can also write a program that copy Gatsby .cache in and out of netlify cache _before_ `gatsby build`. The user experience won't be as easy, but it's not that much more difficult either; plus, it can serve as a general purpose plugin for other SSG that targets Netlify.

I think that's the best way to solve this... what do you think?

cc @axe312ger -- we found out that Gatsby empty the cache copied over by `gatsby-plugin-netlify-cache`, since the previous `oldPluginHash` wasn't there when Gatsby's redux store was initialized. Due to this, the cache wasn't as effective as it's supposed to be.

**Comment by axe312ger** [comment] 2019-10-10 10:26
The netlify plugin just restores the `.cache` folder, while processed assets might be stored somewhere else.

Some processed assets are stored in `node_modules/.cache`, you might want to add that folder to `extraDirsToCache `

This could help speed things up :)

**Comment by axe312ger** [comment] 2019-10-10 10:27
You might also cache some folders in your `public` directory but this can result in bloat of the cache with old files

**Comment by jamessimone** [comment] 2019-10-10 10:28
Amazing work, again. I had tried to contact @axe312ger when I first encountered this issue and raised a github issue on his plugin, without success or response. 

That said, I agree that it should be simple to have a more generic program copy the cache before running gatsby build. It would be a huge benefit to the community!

**Comment by d4rekanguok** [comment] 2019-10-10 11:06
@axe312ger Ah that's interesting, thanks for your speedy response! I'm sure that information will help when I get a bit further, like caching babel & sharp stuff I think?

I found the issue here is not with processed asset -- this plugin's cache entry (and other, such as remark) was discarded (i.e reference to node id) when Gatsby runs bootstrap. This happens even if `public` was added to the directory list.

If you're interested in digging a bit further, I've made a repro repo here:

https://github.com/d4rekanguok/gatsby-remote-images-debug

- Run the image server, then do a `gatsby build` in `./gatsby-site`. If thing goes as planned, it'll send a GET request to the running image server.
- Run `gatsby build` again. This time, servers log no request.
- Run `yarn test:cache` in the root folder (1 directory up from `./gatsby-site`). This will log 1 more request to the image server.
- Run `yarn test:cache` again. This will again log 1 more request to the image server.

It actually took me a while to pinpoint the issue. Here's something I tried that show me where it was:
- I throw an error right after `gatsby-plugin-netlify-cache` completed copying the cache folder over. This exit the gatsby build process. When I inspect the copied over `.cache`, all entries are stored (the one I care about is `.cache/caches/gatsby-remark-images-anywhere`).
- I throw an error right before my plugin try to access the cache. This time, when I inspect the cache, all folders are empty.

When I add a console.log right [before this line of code](https://github.com/gatsbyjs/gatsby/blob/561d33e2e491d3971cb2a404eec9705a5a493602/packages/gatsby/src/bootstrap/index.js#L183), it logs `undefined` with `gatsby-plugin-netlify-cache`; but it logs the proper hash if it's the regular gatsby build.

**Comment by axe312ger** [comment] 2019-10-10 12:59
I feel like this is a problem of how gatsby handles the cache invalidation? 🤔

**Comment by d4rekanguok** [comment] 2019-10-10 16:51
> I feel like this is a problem of how gatsby handles the cache invalidation? 🤔

I agree, though it's difficult for Gatsby to change that. It looks like Gatsby needs the redux store to run the plugins; it's possible to read the redux store from hash but then some sort of reconciling need to happen, which sounds difficult.

`gatsby-plugin-netlify-cache` seems to still reduce the build time on Netlify, so maybe this is not a big issue for it... It doesn't work with this plugin though, so I guess I'll have to look for another solution :(

**Comment by d4rekanguok** [comment] 2019-10-10 18:16
@jamessimone just a quick & dirty PoC. I tested it out with my image server & Gatsby doesn't send any extra image requests on subsequent builds. Could you test it out with your site?

https://github.com/d4rekanguok/netlify-ssg-cache

**Comment by jamessimone** [comment] 2019-10-10 19:51
@d4rekanguok - after looking over your PoC, it seems unlikely you meant for
it to be used in tandem with the existing netlify cache plugin. I went
ahead and installed it on a branch with deploy previews on my site, added
your new package to my package.json, modified my netlify.toml to use the
netlify:build command, and added that to my package.json scripts as well.
Unfortunately, the deploy preview seemed pretty upset.

First, the console statements for the build were repetitively duplicated,
this one being the primary offender but the regular console statements
caused by Netlify installing dependencies and then Gatsby's own output were
streaming by repeated as well: `WARN lifecycle The node binary used for
scripts is /tmp/yarn--1570735894857-0.265146341432166/node but npm is using
/opt/buildhome/.nvm/versions/node/v10.16.3/bin/node itself. Use the
`--scripts-prepend-node-path` option to include the path for the node
binary npm was executed with.`

There were two errors thrown that I saw: ` Error: ENOENT: no such file or
directory, open '/opt/build/repo/.cache/fragmen
ts/image-sharp-fragments.js'`

And: `You specified a fileNode, but we caught an error. First check that
you have gatsby-source-filesystem installed?
3:33:32 PM: failed to process
https://dl.airtable.com/.attachments/1e9cbcb06edf1928d7610fc301307c28/78f4ce62/2019-10-0813.47.05.jpg
3:33:32 PM: Error: ENOENT: no such file or directory, stat
'/opt/build/repo/.cache/gatsby-source-filesystem/tmp-46b0e3af61ff545694aad48c35d6becb.jpg'`

That last one also includes one of my remote images, as you'll see ....

**Comment by d4rekanguok** [comment] 2019-10-11 05:44
@jamessimone Wow, that looks bad. Also thanks for trying this out so quickly - let's continue the discussion over the new repo!

**Closed by d4rekanguok** 2019-10-11 05:44 UTC

**Comment by axe312ger** [comment] 2019-10-11 09:48
I wanted to cache assets outside of netlify, without using payed cloud services. I came up with: https://github.com/axe312ger/gatsby-plugin-sftp-cache

Maybe this can help here? 🤔

**Comment by d4rekanguok** [comment] 2019-10-11 10:09
@axe312ger I checked out the repo and was about to say (I love the idea, I was looking to set it up with s3) I doubt that it'll help since as long as the cache is copied over during onPreInit, some of it will be invalidated by Gatsby.

Then it hits me: what if the cache if copied over _after_ gatsby does its check instead? I modified `gatsby-plugin-netlify-cache` to run on `onPreBootstrap` instead of `onPreInit`, and... it worked. Gatsby stop sending requests to the image server on subsequent builds.

It looks like we might potentially run into issues by sneaking through Gatsby's cache invalidation process, however. Maybe some sort of selective copying could help? i.e only copy `.cache/caches` over during `onPreBootstrap`

**Comment by axe312ger** [comment] 2019-10-11 12:11
We could make your change configurable. Or let the user decide which folders to cache when 🤔

**Comment by d4rekanguok** [comment] 2019-10-15 05:00
@axe312ger Letting user decide which folders to cache when sounds great, could also allow them to specify when to expire the folder as well!

I do wonder if sneaking past Gatsby cache invalidation check is a good thing, though.

**Comment by axe312ger** [comment] 2019-10-21 14:25
> I do wonder if sneaking past Gatsby cache invalidation check is a good thing, though.

I agree here, the whole problem should be solved closer to Gatsby core
